-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 17:03:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mini Twitter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mini Twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mini Twitter` DEFAULT CHARACTER SET utf8 ;
USE `Mini Twitter` ;

-- -----------------------------------------------------
-- Table `Mini Twitter`.` users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mini Twitter`.` users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  ` password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT  CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mini Twitter`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mini Twitter`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `visibility` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `users.id`
    FOREIGN KEY (`id`)
    REFERENCES `Mini Twitter`.` users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mini Twitter`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mini Twitter`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` VARCHAR(45) NOT NULL,
  `user_id` INT NULL,
  `content` TEXT NOT NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `posts.id`
    FOREIGN KEY ()
    REFERENCES `Mini Twitter`.`comments` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `Mini Twitter`.` users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ` posts.id`
    FOREIGN KEY (`id`)
    REFERENCES `Mini Twitter`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mini Twitter`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mini Twitter`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`, `post_id`),
  CONSTRAINT ` users.id`
    FOREIGN KEY (`id`)
    REFERENCES `Mini Twitter`.` users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posts.id`
    FOREIGN KEY (`id`)
    REFERENCES `Mini Twitter`.` users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mini Twitter`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mini Twitter`.`audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `audit_logcol` VARCHAR(64) NOT NULL,
  `operation` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `record_id` BIGINT NOT NULL,
  `changed_by_user_id` INT NOT NULL,
  `details` TEXT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `Mini Twitter`;

DELIMITER $$
USE `Mini Twitter`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Mini Twitter`.`posts_BEFORE_INSERT` BEFORE INSERT ON `posts` FOR EACH ROW
BEGIN
declare msg varchar(255);

 if new_content is null or char_length(trim(new.content)) < 5 then
 signal sqlstate '45000'
 set message_text = 'Conteúdo do post deve ter pelo menos 5 caracteres não vazios.';
 end if;
END$$

USE `Mini Twitter`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Mini Twitter`.`comments_BEFORE_INSERT` BEFORE INSERT ON `comments` FOR EACH ROW
BEGIN
declare msg varchar(255);

if new.content is null or new.content = '' then
signal sqlstate '45000'
set message_text='Não pode haver comentários em branco';
end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
